version: "3.7"
services:
 postgres:
     image: postgis/postgis:12-2.5-alpine
     environment:
       POSTGRES_USER: salon_app
       POSTGRES_PASSWORD: test_db_password
     ports: 
       - '5432:5432'
     volumes:
       - salon_app_postgres:/var/lib/postgresql/data
 redis:
     image: redis:5.0.7
     ports:
       - '6379:6379'
     volumes:
       - salon_app_redis:/var/lib/redis/data
 swagger:
     image: swaggerapi/swagger-ui
     ports:
       - '8080:8080'
     environment:
       API_URL: http://localhost/pages/api_doc
 salon_app:
     stdin_open: true
     tty: true
     build:
       context: .
       args:
         USER_ID: "${USER_ID:-1000}"
         GROUP_ID: "${GROUP_ID:-1000}"
     command:
       - bundle
       - exec
       - puma
       - -C
       - /opt/app/config/puma.rb
     links:
       - postgres
       - redis
     volumes:
       - ./:/opt/app
     ports:
       - '3000:3000'
     env_file:
       - .env
 sidekiq:
     build:
       context: .
       args:
         USER_ID: "${USER_ID:-1000}"
         GROUP_ID: "${GROUP_ID:-1000}"
     command:
       - bundle
       - exec
       - sidekiq
     links:
       - postgres
       - redis
     env_file:
       - .env
 nginx:
     build:
       context: .
       dockerfile: ./Dockerfile.nginx
     links:
       - salon_app
     ports:
       - '80:80'
volumes:
 salon_app_postgres:
 salon_app_redis:
